### ISSUE TITLE
3 column recent posts

### ISSUE THREAD

**Issue by zatziky** [TryGhost/Editorial#15]
Hey there,

is it possible to simply change **2 column layout** to a **3 column one**? I was playing with some vars in **_posts.scss** like `width: calc(#{(100% / 3)} - #{$gutter});` and `$gutter: (_size(gutter) * 2);` but no luck. The layout still have 2 columns:

![image](https://user-images.githubusercontent.com/2794365/56865977-e360bc00-69dc-11e9-8c99-826d00d5c14d.png)

Can you please point me how to achieve it? Thank you. ✌

**Comment by kevinansfield** [comment]
Hey @zatziky 👋 We use GitHub solely for bug tracking, if you need help or support with themeing, please use [our forum](https://forum.ghost.org). There is a [themes  category](https://forum.ghost.org/c/themes) specifically for this purpose where the community can help you 😄
