### ISSUE TITLE
Hamburger Menu has "Toogle" in the background.

### ISSUE THREAD

**Issue by andrei-vintila** [TryGhost/Editorial#33]
Can be seen on demo site also. https://editorial.ghost.io/
![image](https://user-images.githubusercontent.com/8842887/71562679-94e44f80-2a8c-11ea-957a-99650054f190.png)

**Comment by edgeform** [comment]
#31 has this covered and I can confirm it working in a private clone.

**Comment by minimaluminium** [comment]
Hey @Shoane, are you still seeing this issue on the demo site? I just checked this on Chrome and Firefox, but couldn't reproduce on my end. [This line](https://github.com/TryGhost/Editorial/blob/master/assets/main/sass/layout/_sidebar.scss#L98) of CSS should be indenting the text, so it shouldn't appear behind the burger icon.

**Comment by andrei-vintila** [comment]
@minimaluminium yes it appears to have been fixed and I can confirm it might of been cause by something external as this [website ](https://civismogosoaia.ro/) has not been touched for more than one year.
