### ISSUE TITLE
Make post text bigger

### ISSUE THREAD

**Issue by rheahayworth** [TryGhost/Editorial#51]
I'm new to the code and developer world. The editorial paragraph text on posts and pages is very small. How would I go about making the font bigger? There are areas where the text is triggering warnings due to how small it is.

**Comment by minimaluminium** [comment]
Hey @rheahayworth, the best place to add some CSS customization would be `Code injection > Site Header` field on your Ghost admin. For example, you can add this piece of CSS and change the font size values the way you like them. Those are the current values.

```html
<style>
body,input,select,textarea {
    font-size: 13pt;
}

@media screen and (max-width: 1680px) {
    body,input,select,textarea {
        font-size: 11pt;
    }
}

@media screen and (max-width: 1280px) {
    body,input,select,textarea {
        font-size: 10pt;
    }
}

@media screen and (max-width: 360px) {
    body,input,select,textarea {
        font-size: 9pt;
    }
}
</style>
```
