### ISSUE TITLE
Different Color Themes

### ISSUE THREAD

**Issue by Rubix982** [TryGhost/Editorial#54]
Hello!

New to ghost and editorial, so I may not exactly know, but is there a way to change the color scheme to something else? I was looking for a dark color scale instead. Would love an variation that does this.

Thank you!

**Comment by minimaluminium** [comment]
Hey @Rubix982,

Once you clone the theme, install the dependencies with `yarn` and run `yarn dev`, you can find the colors used in the theme in [/assets/main/sass/libs/_vars.scss](https://github.com/TryGhost/Editorial/blob/master/assets/main/sass/libs/_vars.scss#L35-L44) file. When you change the colors, the Sass file will be compiled and assets will be generated automatically.

**Comment by Rubix982** [comment]
Thank you, @minimaluminium!
