### ISSUE TITLE
No support for the new "members only" section and "subscribe"

### ISSUE THREAD

**Issue by ChrisSparksNM** [TryGhost/Editorial#56]
Currently, Casper has a subscribe button on every page, but with your theme there is no Subscribe button.

**Comment by minimaluminium** [comment]
Hey @chrissparksnj, Ghost's new feature Portal has many helpful links which you can use in your site menu. For example, add a menu item with a URL https://site.com/#/portal/signup in the menu and the menu item will open Portal's subscribe popup.

All the available links can be found in Labs > Members > Portal settings > Links. Make sure you're using the latest version of Ghost as the Portal was added in Ghost v3.37.0.
